version: "3.9"
networks:
  mvcdocuments_network:
    driver: bridge
services:
  app: 
    container_name: MvcDocuments
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mvcdocuments_network
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_HOST: postgres
      POSTGRES_DB: MvcDocuments
    ports:
      - "5432:5432"
    networks:
      - mvcdocuments_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:      


# MvcDocuments    
